name: Build and Deploy Sculptor

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    name: Building project
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Node setup
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install
        run: npm install

      - name: Build
        run: npm run build --if-present

      - continue-on-error: false
        env:
          CI: false
